name: Publicar no NuGet

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Empacotar e preparar para publicação
        run: dotnet pack OpenBase.CLI.csproj --configuration Release -o ./packages
      
      - name: Publicar no NuGet
        env:
          NUGET_API_KEY: "${{ secrets.NUGET_API_KEY }}"
        run: |
          dotnet nuget push "./packages/*.nupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json